### ISSUE TITLE
mcraft.fun not displaying wooden_axe when player is holding

### ISSUE THREAD

**Issue by rohanpaleja27** [zardoy/prismarine-web-client#234] opened 2024-11-25 19:56 UTC
Hi, 

I was attempting to play MC using mcraft.fun and noticed that only certain objects are visible when holding. Is this an intended feature?

Thanks,

**Comment by zardoy** [comment] 2024-11-25 23:51
Yes.

**Comment by rohanpaleja27** [comment] 2024-11-26 02:02
Thanks for the clarification. I'll close this issue.

**Comment by zardoy** [comment] 2024-11-26 10:38
duplicate of https://github.com/zardoy/minecraft-web-client/issues/229

**Closed as not planned by zardoy** 2024-11-26 10:38 UTC
